http:
  address: "0.0.0.0:8000"

pgsql:
  dsn: "host=localhost user=postgres password=12345678 dbname=sms_gateway port=5432 sslmode=disable TimeZone=Asia/Tehran"
  migrations_path: "file://migrations"

log_level: Debug
